version: '3.4'
services:
  compile:
    build:
      context: docker/
      target: dever
      ssh: [default]
      # args:
      #   - FROM_IMAGE=osrf/ros:galactic-desktop
    image: hackathon_fira:devel
    extends:
      file: docker/common.yml
      service: base
    command: 'colcon build --symlink-install'

  demo:
    image: hackathon_fira:devel
    extends:
      file: docker/common.yml
      service: x11_base
      # service: x11_gpu  # use this one if you want to use the GPU
    depends_on:
      compile:
        condition: service_completed_successfully
    command: 'ros2 launch fira_hackathon_demo demo.launch.py'

  challenge1:
    extends:
      service: demo
    profiles: [chal1]
    command: 'ros2 launch fira_hackathon_demo challenge1.launch.py mode:=simulation_4dv'

  challenge2:
    extends:
      service: demo
    profiles: [chal2]
    command: 'ros2 launch fira_hackathon_demo challenge2.launch.py mode:=simulation_4dv'

  challenge3:
    extends:
      service: demo
    profiles: [chal3]
    command: 'ros2 launch fira_hackathon_demo challenge3.launch.py mode:=simulation_4dv'
