version: '3.4'
services:
  base:
    build:
      context: ./
      target: dever
      ssh: [default]
    image: hackathon_fira:devel
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - $HOME:$HOME
    environment:
      - WORKSPACE=$PWD
      - USER
      - ROS_IP
      - ROS_MASTER_URI
    network_mode: host

  x11_base:
    extends:
      service: base
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR
    environment:
      - DISPLAY
      - GAZEBO_RESOURCE_PATH=$GAZEBO_RESOURCE_PATH:$PWD/gazebo
      - GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:$PWD/gazebo/models
      - GAZEBO_TEST=$GAZEBO_MODEL_PATH:$PWD/gazebo/models
      - XDG_RUNTIME_DIR
    privileged: true

