version: '3.4'
services:
  base:
    build:
      context: ./
      target: dever
      ssh: [default]
      args:
        - FROM_IMAGE=osrf/ros:galactic-desktop
    image: hackathon_fira:galactic
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - $PWD:$PWD
    environment:
      - WORKSPACE=$PWD
      - USER
    network_mode: host

  x11_base:
    extends:
      service: base
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR
      - $HOME:$HOME
    environment:
      - DISPLAY
      - XDG_RUNTIME_DIR
      - GAZEBO_RESOURCE_PATH=$PWD/gazebo
      - GAZEBO_MODEL_PATH=$PWD/gazebo/models
      - GAZEBO_TEST=$PWD/gazebo/models
    devices:
      - /dev/input/  # for joypads
      - /dev/dri/    # for graphic card
    # privileged: true
